name: Benchmark
on:
  push:
    branches: [main]

jobs:
  bench:
    name: Cargo bench (check compile)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo bench --no-run
